### ISSUE TITLE
Intermittent stack deploy errors

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-api#75]
##### Curl request to localhost
```
curl 'http://127.0.0.1:8080/stacks' -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-AU,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: http://127.0.0.1:4200/stacks/create' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTM2OTMyOTMyfQ.ksJu8sQ9GD2dVheHN5h-TW3dFU6tp4lcQal4EVp71IY' -H 'Content-Type: application/json' -H 'Origin: http://127.0.0.1:4200' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data '{"stackName":"DASTACK","stackFile":"dmVyc2lvbjogJzMnCgpzZXJ2aWNlczoKICBtYWhTZXJ2aWNlOgogICAgaW1hZ2U6IG5naW54Cg=="}' -D -
```

##### Curl response from localhost
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Content-Length: 36
ETag: W/"24-hIkj1S2rR4ZvUJpynEQrGMleEXY"
Date: Wed, 19 Sep 2018 16:09:20 GMT
Connection: keep-alive

Creating service DASTACK_mahService
```
##### Curl response (Changed url and tokens) from docks.evert.io
```
HTTP/2 200 
access-control-allow-origin: *
content-type: text/html; charset=utf-8
date: Wed, 19 Sep 2018 16:12:01 GMT
etag: W/"45-HZWxL3WnTJnv535ni9/w58zo2to"
x-powered-by: Express
content-length: 69

Creating network DASTACK_default
Creating service DASTACK_mahService
```

##### Decoded stack file
```
version: '3'

services:
  mahService:
    image: nginx
```

##### Docker version on localhost
```
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
```

##### Docker version in container on localhost
```
$ docker -v
Docker version 18.06.0-ce, build 0ffa825
```

##### Stack file for deploying Docks API
```
version: '3.2'

services:

  api:
    image: tripleparity/docks-api:branch-sequelize-migrations-_72
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=changeme
      - DOCKS_DB_ADDRESS=db
      - POSTGRES_PASSWORD=example
    ports:
      - '8080:8080'
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres
    volumes:
      - type: volume
        source: docks_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example

volumes:
  docks_data:
```

##### Docks API stack file on production
```
version: '3.2'

services:

  api:
    image: tripleparity/docks-api:branch-develop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - default
      - traefik-net
    deploy:
      labels:
<snip>
      placement:
        constraints: [node.hostname == victor]
    environment:
      - JWT_SECRET=<snip>

  db:
    image: postgres
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=<snip>
    volumes:
      - type: volume
        source: docks_data
        target: /var/lib/postgresql/data

    deploy:
      placement:
        constraints: [node.hostname == victor]

networks:
  default:
  traefik-net:
    external: true

volumes:
  docks_data:
    driver: local
```
